name: lints_extra
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  analyzer: ^5.7.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
